version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: viralops
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    restart: always
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=django-production-key-change-me
      - DEBUG=True
      - ALLOWED_HOSTS=*
      - DB_ENGINE=mysql
      - DB_NAME=viralops
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_HOST=db
      - DB_PORT=3306
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CELERY_TASK_ALWAYS_EAGER=False
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - db
      - redis

  celery:
    build: ./backend
    restart: always
    command: celery -A viralops worker --loglevel=info
    volumes:
      - ./backend:/app
    environment:
      - SECRET_KEY=django-production-key-change-me
      - DEBUG=True
      - DB_ENGINE=mysql
      - DB_NAME=viralops
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_HOST=db
      - DB_PORT=3306
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CELERY_TASK_ALWAYS_EAGER=False
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - redis
      - db

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  mysql_data:
