services:
  - type: web
    name: viralops-web
    env: python
    region: ohio
    plan: free
    rootDir: backend
    buildCommand: "./build.sh"
    startCommand: "./start.sh"
    healthCheckPath: "/healthz/"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: viralops.settings.staging
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        sync: false # Set in dashboard
      - key: CELERY_BROKER_URL
        sync: false # Set in dashboard
      - key: SECRET_KEY
        generateValue: true
      - key: SECURE_SSL_REDIRECT
        value: "True"
      - key: FRONTEND_URL
        value: "https://www.vishnumadapakula.in"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://www.vishnumadapakula.in,https://vishnumadapakula.in"
      - key: GEMINI_API_KEY
        sync: false # Set in dashboard

  - type: worker
    name: viralops-celery-worker
    env: python
    region: ohio
    rootDir: backend
    buildCommand: "./build.sh"
    startCommand: "celery -A viralops worker --loglevel=info"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: viralops.settings.staging
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        sync: false
      - key: CELERY_BROKER_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: SECURE_SSL_REDIRECT
        value: "True"
      - key: FRONTEND_URL
        value: "https://www.vishnumadapakula.in"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://www.vishnumadapakula.in,https://vishnumadapakula.in"
      - key: GEMINI_API_KEY
        sync: false

  - type: worker
    name: viralops-celery-beat
    env: python
    region: ohio
    rootDir: backend
    buildCommand: "./build.sh"
    startCommand: "celery -A viralops beat --loglevel=info"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: viralops.settings.staging
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        sync: false
      - key: CELERY_BROKER_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: SECURE_SSL_REDIRECT
        value: "True"
      - key: FRONTEND_URL
        value: "https://www.vishnumadapakula.in"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://www.vishnumadapakula.in,https://vishnumadapakula.in"
      - key: GEMINI_API_KEY
        sync: false
