# Generated by Django 5.2.14 on 2026-06-03 13:04

import django.db.models.deletion
import organizations.mixins
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_workspaceinvite'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_subscription_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('razorpay_customer_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAST_DUE', 'Past Due'), ('CANCELLED', 'Cancelled'), ('PENDING', 'Pending')], default='PENDING', max_length=20)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancel_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
            bases=(organizations.mixins.TenantScopedQuerysetMixin, models.Model),
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_payment_id', models.CharField(max_length=100)),
                ('razorpay_order_id', models.CharField(max_length=100)),
                ('razorpay_signature', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('CAPTURED', 'Captured'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded'), ('AUTHORIZED', 'Authorized')], max_length=20)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.subscription')),
            ],
            bases=(organizations.mixins.TenantScopedQuerysetMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razorpay_invoice_id', models.CharField(blank=True, max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('GENERATED', 'Generated'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('VOID', 'Void')], default='GENERATED', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.subscription')),
            ],
            bases=(organizations.mixins.TenantScopedQuerysetMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('FREE', 'Free'), ('PRO', 'Pro'), ('TEAMS', 'Teams'), ('ENTERPRISE', 'Enterprise')], max_length=50, unique=True)),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price_yearly', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('razorpay_plan_id', models.CharField(blank=True, max_length=100)),
                ('max_projects', models.IntegerField(default=5)),
                ('max_generations_per_month', models.IntegerField(default=100)),
                ('max_storage_gb', models.IntegerField(default=10)),
                ('ai_brand_tone', models.BooleanField(default=False)),
                ('custom_domain', models.BooleanField(default=False)),
                ('priority_support', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            bases=(organizations.mixins.TenantScopedQuerysetMixin, models.Model),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='billing.subscriptionplan'),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('tenant', 'user')},
        ),
    ]
