# Generated by Django 5.2.14 on 2026-06-03 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='razorpay_invoice_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='razorpay_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
