# Generated by Django 5.2.14 on 2026-06-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_invoice_razorpay_invoice_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='billing_address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='subscription',
            name='billing_contact',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='subscription',
            name='billing_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='subscription',
            name='gstin',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
        migrations.AddField(
            model_name='subscription',
            name='legal_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
