# Generated by Django 5.2.14 on 2026-05-28 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('HOOK', 'Hook Option'), ('TITLE', 'Title Variant'), ('CAPTION', 'Caption'), ('CTA', 'CTA Variant'), ('HASHTAG', 'Hashtag Set'), ('THUMBNAIL', 'Thumbnail Copy'), ('SCRIPT', 'Short Script'), ('PLATFORM_PACK', 'Platform Asset Bundle')], max_length=20)),
                ('platform', models.CharField(choices=[('SHORTS', 'YouTube Shorts'), ('REELS', 'Instagram Reels'), ('TIKTOK', 'TikTok'), ('MULTI', 'Cross-Platform')], default='MULTI', max_length=20)),
                ('content', models.TextField(help_text='Standard content text or JSON string')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional JSON metadata (e.g. timestamps, visual prompts)')),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='organizations.organization')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedAssetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='projects.generatedasset')),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_assets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='organizations.organization')),
            ],
        ),
        migrations.AddField(
            model_name='generatedasset',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='projects.project'),
        ),
        migrations.CreateModel(
            name='SourceInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('VIDEO', 'Video Upload'), ('AUDIO', 'Audio Upload'), ('YOUTUBE', 'YouTube Link'), ('ARTICLE', 'Article/Blog Text'), ('TRANSCRIPT', 'Raw Transcript'), ('SCRIPT', 'Raw Script'), ('PDF', 'PDF Text')], max_length=20)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('source_url', models.URLField(blank=True, default='')),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('text_content', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Ingestion'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_log', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='projects.project')),
                ('source_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='projects.sourceinput')),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('HOOK', 'Hook Template'), ('CTA', 'CTA Template'), ('SCRIPT', 'Script Format')], max_length=20)),
                ('content', models.TextField(help_text="Template structure with variables, e.g. 'How to {{action}} without {{pain}}'")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='organizations.organization')),
            ],
        ),
        migrations.CreateModel(
            name='TranscriptRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField()),
                ('normalized_text', models.TextField()),
                ('segments', models.JSONField(default=list, help_text='List of JSON segments with start, end, speaker, text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_input', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='projects.sourceinput')),
            ],
        ),
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('TRANSCRIPTION_MINUTES', 'Transcription Minutes'), ('AI_GENERATION', 'AI Content Generation')], max_length=30)),
                ('quantity', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to='organizations.organization')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MemoryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('BRAND_TONE', 'Brand Tone & Voice'), ('STYLE_GUIDE', 'Style Guide'), ('PREFERRED_HOOKS', 'Preferred Hooks & Structures'), ('PAST_APPROVED_PATTERNS', 'Past Approved Patterns')], max_length=50)),
                ('value', models.JSONField(help_text='JSON payload containing configuration details')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memories', to='organizations.organization')),
            ],
            options={
                'unique_together': {('organization', 'key')},
            },
        ),
    ]
