# Generated by Django 5.2.14 on 2026-06-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceinput',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='sources/%Y/%m/%d/'),
        ),
    ]
