# Generated by Django 5.2.14 on 2026-06-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_socialpublishrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourceinput',
            name='transcript_length',
            field=models.IntegerField(blank=True, help_text='Length of retrieved transcript in characters', null=True),
        ),
        migrations.AddField(
            model_name='sourceinput',
            name='transcript_preview',
            field=models.TextField(blank=True, default='', help_text='First 500 characters of the retrieved transcript'),
        ),
        migrations.AddField(
            model_name='sourceinput',
            name='transcript_retrieval_method',
            field=models.CharField(blank=True, default='', help_text="Method used to retrieve transcript (e.g. 'youtube-transcript-api/manual-en')", max_length=100),
        ),
        migrations.AddField(
            model_name='sourceinput',
            name='transcript_retrieved_at',
            field=models.DateTimeField(blank=True, help_text='UTC timestamp when the transcript was retrieved', null=True),
        ),
        migrations.AddField(
            model_name='sourceinput',
            name='transcript_source',
            field=models.CharField(blank=True, default='', help_text="Source type used for transcript retrieval (e.g. 'youtube')", max_length=50),
        ),
        migrations.AddField(
            model_name='sourceinput',
            name='transcript_validation_status',
            field=models.CharField(blank=True, default='', help_text='PASS or FAIL — result of TranscriptValidator', max_length=10),
        ),
    ]
