# Generated by Django 5.2.14 on 2026-06-05 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_add_transcript_diagnostics_to_sourceinput'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentIntelligenceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True, default='', help_text='AI-generated 2-3 sentence summary')),
                ('topics', models.JSONField(default=list, help_text='List of main topic strings')),
                ('keywords', models.JSONField(default=list, help_text='List of keyword strings')),
                ('entities', models.JSONField(default=list, help_text='Named entities: people, brands, places')),
                ('emotional_moments', models.JSONField(default=list, help_text='High-emotion transcript segments')),
                ('viral_score', models.IntegerField(default=0, help_text='Overall virality potential 0-100')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intelligence', to='projects.project')),
                ('source_input', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intelligence', to='projects.sourceinput')),
            ],
        ),
        migrations.CreateModel(
            name='Moment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('HOOK', 'Hook Moment'), ('VIRAL', 'Viral Moment'), ('STORY', 'Story Moment'), ('EMOTIONAL', 'Emotional Moment'), ('EDUCATIONAL', 'Educational Moment'), ('CTA', 'CTA Moment')], max_length=20)),
                ('score', models.IntegerField(default=0, help_text='Viral/engagement score 0-100')),
                ('start_time', models.CharField(blank=True, default='', help_text="e.g. '0:45' or '45.2'", max_length=20)),
                ('end_time', models.CharField(blank=True, default='', help_text="e.g. '1:30' or '90.5'", max_length=20)),
                ('excerpt', models.TextField(blank=True, default='', help_text='Transcript excerpt for this moment')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional scoring data, visual prompts, etc.')),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moments', to='projects.project')),
                ('source_input', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moments', to='projects.sourceinput')),
            ],
            options={
                'ordering': ['-score', 'created_at'],
            },
        ),
    ]
