# Generated by Django 5.2.14 on 2026-06-05 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_add_moment_and_intelligence'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedasset',
            name='moment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_assets', to='projects.moment'),
        ),
        migrations.AddField(
            model_name='moment',
            name='video_clip_url',
            field=models.URLField(blank=True, default='', help_text='URL to the generated clip video'),
        ),
        migrations.CreateModel(
            name='TranscriptSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.FloatField(default=0.0)),
                ('end_time', models.FloatField(default=0.0)),
                ('text', models.TextField(blank=True, default='')),
                ('speaker', models.CharField(blank=True, default='', max_length=255)),
                ('segment_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transcript_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_list', to='projects.transcriptrecord')),
            ],
            options={
                'ordering': ['segment_index', 'start_time'],
            },
        ),
        migrations.AddField(
            model_name='moment',
            name='segments',
            field=models.ManyToManyField(blank=True, related_name='moments', to='projects.transcriptsegment'),
        ),
    ]
