# Generated by Django 5.2.14 on 2026-06-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_processingjob_last_retry_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingjob',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('RETRYING', 'Retrying'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PARTIAL_SUCCESS', 'Partial Success')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('RETRYING', 'Retrying'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PARTIAL_SUCCESS', 'Partial Success')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='sourceinput',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Ingestion'), ('PROCESSING', 'Processing'), ('RETRYING', 'Retrying'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PARTIAL_SUCCESS', 'Partial Success')], default='PENDING', max_length=20),
        ),
    ]
