# Generated by Django 5.2.14 on 2026-06-24 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_workspaceinvite'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(blank=True, max_length=255, null=True)),
                ('brand_voice', models.TextField(blank=True, null=True)),
                ('audience', models.TextField(blank=True, null=True)),
                ('cta', models.TextField(blank=True, null=True)),
                ('hashtags', models.TextField(blank=True, null=True)),
                ('examples', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brand_kit', to='organizations.organization')),
            ],
        ),
    ]
