# Generated by Django 5.2.14 on 2026-06-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creatorprofile',
            name='content_niches',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='industry',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='creatorprofile',
            name='role',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sessionhistory',
            name='timezone',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
